"""Project validation and deterministic derived configuration generation."""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

from .project_model import ProjectModelError, resolve_project
from .sdk_context import SdkContext


GENERATED_DIRECTORY = Path(".ecos") / "generated"
RESOLVED_PROJECT_FILE = "resolved-project.json"
RESOLVED_CMAKE_FILE = "resolved-project.cmake"
CONFIGURATION_FINGERPRINT_FILE = "configuration.fingerprint"
KCONFIG_ROOT_FILE = "Kconfig"
KCONFIG_CONFIG_FILE = ".config"
KCONFIG_HEADER_FILE = "sdkconfig.h"
KCONFIG_CMAKE_FILE = "sdkconfig.cmake"


class ConfigurationError(RuntimeError):
    """Base error for configuring an ECOS project."""


class ConfigurationDependencyError(ConfigurationError):
    """A required host-side configuration dependency is unavailable."""


class ConfigurationWriteError(ConfigurationError):
    """Derived project configuration could not be written atomically."""


@dataclass(frozen=True)
class ConfigurationResult:
    data: dict[str, Any]
    resolved: dict[str, Any]


def _cmake_quote(value: str) -> str:
    return value.replace("\\", "/").replace(";", "\\;").replace('"', '\\"')


def _cmake_set(name: str, values: list[str]) -> list[str]:
    lines = [f"set({name}"]
    lines.extend(f'    "{_cmake_quote(value)}"' for value in values)
    lines.append(")")
    return lines


def _component_key(component_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", component_id).upper()


def _kconfig_root(sources: list[str]) -> str:
    lines = ['mainmenu "ECOS Embedded SDK Configuration"', ""]
    for source in sources:
        escaped = source.replace("\\", "/").replace('"', '\\"')
        lines.append(f'source "{escaped}"')
    lines.append("")
    return "\n".join(lines)


def _empty_kconfig_outputs() -> tuple[str, str, dict[str, str]]:
    return "", "/* Generated by ecos configure. */\n", {}


def _evaluate_kconfig(
    root_content: str,
    sources: list[str],
    user_config: Optional[str],
    temporary: Path,
) -> tuple[str, str, dict[str, str]]:
    if not sources:
        return _empty_kconfig_outputs()
    try:
        import kconfiglib  # type: ignore
    except ImportError as exc:
        raise ConfigurationDependencyError(
            "Kconfiglib is unavailable; run 'tools/install.py' to install the "
            "SDK's pinned Python dependencies"
        ) from exc

    root_path = temporary / KCONFIG_ROOT_FILE
    root_path.write_text(root_content, encoding="utf-8", newline="\n")
    try:
        kconf = kconfiglib.Kconfig(
            str(root_path),
            warn=False,
            suppress_traceback=True,
            encoding="utf-8",
        )
        if user_config is not None:
            kconf.load_config(user_config, replace=True)
        config_path = temporary / KCONFIG_CONFIG_FILE
        header_path = temporary / KCONFIG_HEADER_FILE
        kconf.write_config(str(config_path))
        kconf.write_autoconf(str(header_path))
    except (OSError, kconfiglib.KconfigError) as exc:
        raise ConfigurationError(f"cannot evaluate project Kconfig: {exc}") from exc

    values = {
        symbol.name: symbol.str_value
        for symbol in kconf.unique_defined_syms
        if symbol.name
    }
    return (
        config_path.read_text(encoding="utf-8"),
        header_path.read_text(encoding="utf-8"),
        dict(sorted(values.items())),
    )


def _sdkconfig_cmake(values: dict[str, str]) -> str:
    lines = ["# Generated by ecos configure. Do not edit."]
    for name, value in sorted(values.items()):
        lines.append(f'set(CONFIG_{name} "{_cmake_quote(value)}")')
    lines.append("")
    return "\n".join(lines)


def _resolved_cmake(resolved: dict[str, Any], generated_dir: Path) -> str:
    build = resolved["build"]
    lines = ["# Generated by ecos configure. Do not edit."]
    lines.extend(_cmake_set("ECOS_APP_SOURCES", build["application_sources"]))
    lines.extend(
        _cmake_set("ECOS_APP_INCLUDE_DIRS", build["application_include_dirs"])
    )
    lines.extend(_cmake_set("ECOS_APP_DEFINES", build["application_defines"]))
    lines.extend(_cmake_set("ECOS_TARGET_SOURCES", build["target_sources"]))
    lines.extend(
        _cmake_set(
            "ECOS_TARGET_CAPABILITY_SOURCES", build["target_capability_sources"]
        )
    )
    lines.extend(_cmake_set("ECOS_TARGET_INCLUDE_DIRS", build["target_include_dirs"]))
    lines.extend(
        _cmake_set("ECOS_REQUIREMENTS", resolved["requirements"]["requested"])
    )
    linker_script = build.get("linker_script") or ""
    lines.append(f'set(ECOS_LINKER_SCRIPT "{_cmake_quote(linker_script)}")')
    lines.append(
        f'set(ECOS_CONFIG_HEADER "{_cmake_quote(str(generated_dir / KCONFIG_HEADER_FILE))}")'
    )
    lines.append(
        f'include("{_cmake_quote(str(generated_dir / KCONFIG_CMAKE_FILE))}")'
    )
    component_keys: list[str] = []
    used_keys: set[str] = set()
    for component in resolved["components"]:
        key = _component_key(component["id"])
        if key in used_keys:
            raise ConfigurationError(
                f"Component IDs collide after CMake normalization: {component['id']}"
            )
        used_keys.add(key)
        component_keys.append(key)
        lines.append(f'set(ECOS_COMPONENT_{key}_ID "{_cmake_quote(component["id"])}")')
        lines.extend(
            _cmake_set(f"ECOS_COMPONENT_{key}_SOURCES", component["sources"])
        )
        lines.extend(
            _cmake_set(
                f"ECOS_COMPONENT_{key}_INCLUDE_DIRS", component["include_dirs"]
            )
        )
        lines.extend(
            _cmake_set(f"ECOS_COMPONENT_{key}_DEFINES", component["defines"])
        )
        dependency_keys = [_component_key(item) for item in component["dependencies"]]
        lines.extend(
            _cmake_set(f"ECOS_COMPONENT_{key}_DEPENDENCIES", dependency_keys)
        )
    lines.extend(_cmake_set("ECOS_COMPONENT_KEYS", component_keys))
    lines.append("")
    return "\n".join(lines)


def _configuration_fingerprint(
    source_fingerprint: str, config_content: str
) -> str:
    digest = hashlib.sha256()
    digest.update(source_fingerprint.encode("ascii"))
    digest.update(b"\0")
    digest.update(config_content.encode("utf-8"))
    return digest.hexdigest()


def _json_content(value: dict[str, Any]) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def _existing_matches(directory: Path, files: dict[str, str]) -> bool:
    if not directory.is_dir():
        return False
    for name, expected in files.items():
        try:
            if (directory / name).read_text(encoding="utf-8") != expected:
                return False
        except OSError:
            return False
    existing = {path.name for path in directory.iterdir()}
    return existing == set(files)


def _replace_generated(directory: Path, files: dict[str, str]) -> None:
    parent = directory.parent
    parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=".generated.ecos-", dir=parent))
    backup: Optional[Path] = None
    installed = False
    try:
        for name, content in files.items():
            (staging / name).write_text(content, encoding="utf-8", newline="\n")
        if directory.exists():
            backup = Path(tempfile.mkdtemp(prefix=".generated.backup-", dir=parent))
            backup.rmdir()
            directory.replace(backup)
        try:
            staging.replace(directory)
            installed = True
        except OSError:
            if backup is not None and backup.exists() and not directory.exists():
                backup.replace(directory)
                backup = None
            raise
        if backup is not None:
            shutil.rmtree(backup)
            backup = None
    except OSError as exc:
        raise ConfigurationWriteError(
            f"cannot replace generated project configuration {directory}: {exc}"
        ) from exc
    finally:
        if not installed and staging.exists():
            shutil.rmtree(staging)
        if backup is not None and backup.exists() and not directory.exists():
            backup.replace(directory)


def validate_project(
    context: SdkContext, *, project_root: Optional[Path] = None
) -> dict[str, Any]:
    """Validate and resolve a project without writing derived files."""

    resolved = resolve_project(context, project_root=project_root)
    return {
        "path": resolved["project"]["root"],
        "sdk": {
            "id": resolved["sdk"]["id"],
            "version": resolved["sdk"]["version"],
        },
        "board": resolved["project"]["board"],
        "target": resolved["project"]["target"],
        "profile": resolved["project"]["profile"],
        "example": resolved["project"]["example"],
        "components": [item["id"] for item in resolved["components"]],
        "requirements": resolved["requirements"],
        "toolchain": resolved["toolchain"],
        "source_fingerprint": resolved["source_fingerprint"],
        "valid": True,
    }


def configure_project(
    context: SdkContext,
    *,
    project_root: Optional[Path] = None,
    dry_run: bool = False,
) -> ConfigurationResult:
    """Resolve a project and atomically generate all CMake/Kconfig inputs."""

    resolved = resolve_project(context, project_root=project_root)
    root = Path(resolved["project"]["root"])
    generated_dir = root / GENERATED_DIRECTORY
    kconfig_sources = resolved["kconfig"]["sources"]
    kconfig_root = _kconfig_root(kconfig_sources)
    with tempfile.TemporaryDirectory(prefix="ecos-configure-") as temporary_name:
        config_content, header_content, values = _evaluate_kconfig(
            kconfig_root,
            kconfig_sources,
            resolved["kconfig"]["user_config"],
            Path(temporary_name),
        )
    configuration_fingerprint = _configuration_fingerprint(
        resolved["source_fingerprint"], config_content
    )
    resolved["configuration"] = {
        "fingerprint": configuration_fingerprint,
        "values": values,
        "generated": {
            "directory": str(generated_dir),
            "kconfig": str(generated_dir / KCONFIG_ROOT_FILE),
            "config": str(generated_dir / KCONFIG_CONFIG_FILE),
            "header": str(generated_dir / KCONFIG_HEADER_FILE),
            "cmake": str(generated_dir / KCONFIG_CMAKE_FILE),
            "resolved_cmake": str(generated_dir / RESOLVED_CMAKE_FILE),
            "resolved_project": str(generated_dir / RESOLVED_PROJECT_FILE),
            "fingerprint": str(generated_dir / CONFIGURATION_FINGERPRINT_FILE),
        },
    }
    files = {
        KCONFIG_ROOT_FILE: kconfig_root,
        KCONFIG_CONFIG_FILE: config_content,
        KCONFIG_HEADER_FILE: header_content,
        KCONFIG_CMAKE_FILE: _sdkconfig_cmake(values),
        RESOLVED_CMAKE_FILE: _resolved_cmake(resolved, generated_dir),
        CONFIGURATION_FINGERPRINT_FILE: configuration_fingerprint + "\n",
    }
    files[RESOLVED_PROJECT_FILE] = _json_content(resolved)
    changed = not _existing_matches(generated_dir, files)
    if changed and not dry_run:
        _replace_generated(generated_dir, files)
    data = {
        "path": str(root),
        "board": resolved["project"]["board"],
        "target": resolved["project"]["target"],
        "profile": resolved["project"]["profile"],
        "source_fingerprint": resolved["source_fingerprint"],
        "configuration_fingerprint": configuration_fingerprint,
        "generated": resolved["configuration"]["generated"],
        "changed": changed,
        "dry_run": dry_run,
    }
    return ConfigurationResult(data=data, resolved=resolved)


def load_resolved_project(project_root: Path) -> dict[str, Any]:
    generated = project_root.resolve() / GENERATED_DIRECTORY
    path = generated / RESOLVED_PROJECT_FILE
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise ConfigurationError(
            f"generated project configuration does not exist: {path}; run 'ecos configure'"
        ) from exc
    except json.JSONDecodeError as exc:
        raise ConfigurationError(f"generated project configuration is invalid: {path}") from exc
    if not isinstance(value, dict) or value.get("schema_version") != 1:
        raise ConfigurationError(f"generated project configuration schema is invalid: {path}")
    configuration = value.get("configuration")
    expected = configuration.get("fingerprint") if isinstance(configuration, dict) else None
    fingerprint_path = generated / CONFIGURATION_FINGERPRINT_FILE
    try:
        recorded = fingerprint_path.read_text(encoding="ascii").strip()
    except OSError as exc:
        raise ConfigurationError(
            f"generated configuration fingerprint does not exist: {fingerprint_path}; "
            "run 'ecos configure'"
        ) from exc
    if not isinstance(expected, str) or len(expected) != 64 or recorded != expected:
        raise ConfigurationError(
            f"generated project configuration fingerprint is invalid: {fingerprint_path}; "
            "run 'ecos configure'"
        )
    return value


__all__ = [
    "ConfigurationDependencyError",
    "ConfigurationError",
    "ConfigurationResult",
    "ConfigurationWriteError",
    "CONFIGURATION_FINGERPRINT_FILE",
    "ProjectModelError",
    "configure_project",
    "load_resolved_project",
    "validate_project",
]
