#!/usr/bin/env bash

# Lightweight ECOS board package discovery. It intentionally supports only the
# simple manifest subset used by ecos-board.yml, so no external YAML tool is
# required on developer machines.

ecos_board_registry_dir() {
    echo "${ECOS_BOARD_REGISTRY:-$HOME/.ecos/boards}"
}

ecos_board_manifest_value() {
    local manifest="$1"
    local key="$2"
    awk -F: -v key="$key" '
        $1 == key {
            sub(/^[[:space:]]+/, "", $2)
            sub(/[[:space:]]+$/, "", $2)
            print $2
            exit
        }
    ' "$manifest"
}

ecos_board_manifest_section_value() {
    local manifest="$1"
    local section="$2"
    local key="$3"
    awk -F: -v section="$section" -v key="$key" '
        $1 == section {
            in_section = 1
            next
        }
        in_section && $0 !~ /^  / {
            exit
        }
        in_section {
            line = $0
            sub(/^  /, "", line)
            split(line, parts, ":")
            if (parts[1] == key) {
                value = substr(line, index(line, ":") + 1)
                sub(/^[[:space:]]+/, "", value)
                sub(/[[:space:]]+$/, "", value)
                print value
                exit
            }
        }
    ' "$manifest"
}

ecos_board_manifest_aliases() {
    local manifest="$1"
    awk '
        $0 == "aliases:" {
            in_aliases = 1
            next
        }
        in_aliases && $0 !~ /^  - / {
            exit
        }
        in_aliases {
            alias = $0
            sub(/^  - /, "", alias)
            print alias
        }
    ' "$manifest"
}

ecos_board_manifest_dir() {
    dirname "$1"
}

ecos_board_iter_manifests() {
    local registry_dir
    registry_dir="$(ecos_board_registry_dir)"

    if [[ -n "${ECOS_SDK_HOME:-}" && -d "$ECOS_SDK_HOME/board" ]]; then
        find "$ECOS_SDK_HOME/board" -mindepth 2 -maxdepth 2 -name ecos-board.yml -type f 2>/dev/null
    fi

    if [[ -n "${ECOS_BOARD_PATH:-}" ]]; then
        local entry
        IFS=: read -r -a entries <<< "$ECOS_BOARD_PATH"
        for entry in "${entries[@]}"; do
            if [[ -f "$entry" ]]; then
                echo "$entry"
            elif [[ -f "$entry/ecos-board.yml" ]]; then
                echo "$entry/ecos-board.yml"
            elif [[ -d "$entry" ]]; then
                find "$entry" -mindepth 1 -maxdepth 2 -name ecos-board.yml -type f 2>/dev/null
            fi
        done
    fi

    if [[ -d "$registry_dir" ]]; then
        find "$registry_dir" -mindepth 1 -maxdepth 2 -name ecos-board.yml -type f 2>/dev/null
    fi
}

ecos_board_matches() {
    local manifest="$1"
    local query="$2"
    local id
    id="$(ecos_board_manifest_value "$manifest" id)"
    [[ "$query" == "$id" ]] && return 0

    local alias
    while IFS= read -r alias; do
        [[ "$query" == "$alias" ]] && return 0
    done < <(ecos_board_manifest_aliases "$manifest")

    return 1
}

ecos_board_find_manifest() {
    local query="$1"
    local manifest
    while IFS= read -r manifest; do
        if ecos_board_matches "$manifest" "$query"; then
            echo "$manifest"
            return 0
        fi
    done < <(ecos_board_iter_manifests | awk '!seen[$0]++')
    return 1
}

ecos_board_print_list() {
    local manifest id name aliases source
    printf "%-18s %-14s %-24s %s\n" "ID" "ALIASES" "NAME" "PATH"
    while IFS= read -r manifest; do
        id="$(ecos_board_manifest_value "$manifest" id)"
        name="$(ecos_board_manifest_value "$manifest" name)"
        aliases="$(ecos_board_manifest_aliases "$manifest" | paste -sd, -)"
        source="$(ecos_board_manifest_dir "$manifest")"
        printf "%-18s %-14s %-24s %s\n" "$id" "$aliases" "$name" "$source"
    done < <(ecos_board_iter_manifests | awk '!seen[$0]++')
}

ecos_board_abs_path() {
    local base="$1"
    local rel="$2"
    [[ -z "$rel" ]] && return 0
    if [[ "$rel" = /* ]]; then
        echo "$rel"
    else
        echo "$base/$rel"
    fi
}

ecos_board_write_project_config() {
    local manifest="$1"
    local output="$2"
    local board_dir id category build_conf board_kconfig driver_kconfig

    board_dir="$(ecos_board_manifest_dir "$manifest")"
    id="$(ecos_board_manifest_value "$manifest" id)"
    category="$(ecos_board_manifest_value "$manifest" category)"
    build_conf="$(ecos_board_manifest_section_value "$manifest" files build_conf)"
    board_kconfig="$(ecos_board_manifest_section_value "$manifest" kconfig board)"
    driver_kconfig="$(ecos_board_manifest_section_value "$manifest" kconfig drivers)"

    mkdir -p "$(dirname "$output")"
    {
        echo "# Generated by ecos set_board. Do not edit by hand."
        echo "BOARD_PACKAGE := $board_dir"
        echo "BOARD_ID := $id"
        echo "BOARD_CATEGORY := $category"
        echo "CATEGORY := $category"
        echo "BOARD_BUILD_CONF := $(ecos_board_abs_path "$board_dir" "$build_conf")"
        echo "BOARD_KCONFIG := $(ecos_board_abs_path "$board_dir" "$board_kconfig")"
        echo "DRIVER_KCONFIG := $(ecos_board_abs_path "$board_dir" "$driver_kconfig")"
    } > "$output"
}
