#ifndef STARRYSKY_T1_PICO_BOARD_H
#define STARRYSKY_T1_PICO_BOARD_H

#include <stdint.h>

/* 定义 StarrySky T1-Pico 的存储器布局。 */
#define STARRYSKY_T1_PICO_FLASH_BASE_ADDR       0x20000000UL
#define STARRYSKY_T1_PICO_FLASH_SIZE_BYTES      0x01000000UL
#define STARRYSKY_T1_PICO_DSRAM_BASE_ADDR       0x01800000UL
#define STARRYSKY_T1_PICO_DSRAM_SIZE_BYTES      0x00004000UL
#define STARRYSKY_T1_PICO_ISRAM_BASE_ADDR       0x01000000UL
#define STARRYSKY_T1_PICO_ISRAM_TEST_SIZE_BYTES 0x00004000UL
#define STARRYSKY_T1_PICO_SDRAM_BASE_ADDR       0x80000000UL
#define STARRYSKY_T1_PICO_SDRAM_SIZE_BYTES      0x02000000UL
#define STARRYSKY_T1_PICO_SDRAM_END_ADDR        (STARRYSKY_T1_PICO_SDRAM_BASE_ADDR + \
                                            STARRYSKY_T1_PICO_SDRAM_SIZE_BYTES)

/* 定义 StarrySky T1-Pico 的板级时钟。 */
#define STARRYSKY_T1_PICO_APB_CLOCK_HZ          20000000UL

/* 定义八位和三十二位易变寄存器访问方法。 */
#define STARRYSKY_T1_PICO_MMIO8(address)        (*(volatile uint8_t *)(uintptr_t)(address))
#define STARRYSKY_T1_PICO_MMIO32(address)       (*(volatile uint32_t *)(uintptr_t)(address))

/* 定义系统串口寄存器。 */
#define STARRYSKY_T1_PICO_UART0_BASE_ADDR       0x10010000UL
#define REG_UART_0_RBR                     STARRYSKY_T1_PICO_MMIO8(STARRYSKY_T1_PICO_UART0_BASE_ADDR + 0x00UL)
#define REG_UART_0_THR                     STARRYSKY_T1_PICO_MMIO8(STARRYSKY_T1_PICO_UART0_BASE_ADDR + 0x00UL)
#define REG_UART_0_DLL                     STARRYSKY_T1_PICO_MMIO8(STARRYSKY_T1_PICO_UART0_BASE_ADDR + 0x00UL)
#define REG_UART_0_DLH                     STARRYSKY_T1_PICO_MMIO8(STARRYSKY_T1_PICO_UART0_BASE_ADDR + 0x04UL)
#define REG_UART_0_LCR                     STARRYSKY_T1_PICO_MMIO8(STARRYSKY_T1_PICO_UART0_BASE_ADDR + 0x0CUL)
#define REG_UART_0_MCR                     STARRYSKY_T1_PICO_MMIO8(STARRYSKY_T1_PICO_UART0_BASE_ADDR + 0x10UL)
#define REG_UART_0_LSR                     STARRYSKY_T1_PICO_MMIO8(STARRYSKY_T1_PICO_UART0_BASE_ADDR + 0x14UL)
#define STARRYSKY_T1_PICO_UART_LSR_DATA_READY   (1u << 0)
#define STARRYSKY_T1_PICO_UART_LSR_TX_READY     (1u << 5)
#define STARRYSKY_T1_PICO_UART_LCR_DLAB         (1u << 7)
#define STARRYSKY_T1_PICO_UART_DIVISOR_MAX      0xFFFFu

/* 定义 I2C0 寄存器。 */
#define STARRYSKY_T1_PICO_I2C0_BASE_ADDR        0x10030000UL
#define REG_I2C_0_CTRL                     STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_I2C0_BASE_ADDR + 0x00UL)
#define REG_I2C_0_PSCR                     STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_I2C0_BASE_ADDR + 0x04UL)
#define REG_I2C_0_TXR                      STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_I2C0_BASE_ADDR + 0x08UL)
#define REG_I2C_0_RXR                      STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_I2C0_BASE_ADDR + 0x0CUL)
#define REG_I2C_0_CMD                      STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_I2C0_BASE_ADDR + 0x10UL)
#define REG_I2C_0_SR                       STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_I2C0_BASE_ADDR + 0x14UL)

/* 定义 QSPI0 寄存器。 */
#define STARRYSKY_T1_PICO_QSPI0_BASE_ADDR       0x10040000UL
#define REG_QSPI_0_CTRLR0                  STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x00UL)
#define REG_QSPI_0_CTRLR1                  STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x04UL)
#define REG_QSPI_0_SSIENR                  STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x08UL)
#define REG_QSPI_0_SER                     STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x10UL)
#define REG_QSPI_0_BAUDR                   STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x14UL)
#define REG_QSPI_0_TXFTLR                  STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x18UL)
#define REG_QSPI_0_RXFTLR                  STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x1CUL)
#define REG_QSPI_0_SR                      STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x28UL)
#define REG_QSPI_0_IMR                     STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x2CUL)
#define REG_QSPI_0_RISR                    STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x34UL)
#define REG_QSPI_0_ICR                     STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x48UL)
#define REG_QSPI_0_DR                      STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0x60UL)
#define REG_QSPI_0_SPI_CTRLR0              STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_QSPI0_BASE_ADDR + 0xF4UL)

/* 定义 GPIO 端口数量和每组可用引脚数量。 */
#define STARRYSKY_T1_PICO_GPIO_PORT_COUNT       4u
#define STARRYSKY_T1_PICO_GPIO_PINS_PER_PORT    8u

/* 定义 GPIO 端口编号。 */
#define STARRYSKY_T1_PICO_GPIO_PORT_A           0u
#define STARRYSKY_T1_PICO_GPIO_PORT_B           1u
#define STARRYSKY_T1_PICO_GPIO_PORT_C           2u
#define STARRYSKY_T1_PICO_GPIO_PORT_D           3u

/* 定义 GPIO 数据、方向和输入寄存器。 */
#define STARRYSKY_T1_PICO_GPIO0_BASE_ADDR       0x10060000UL
#define REG_GPIO_0_SWPORTA_DR              STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x00UL)
#define REG_GPIO_0_SWPORTA_DDR             STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x04UL)
#define REG_GPIO_0_SWPORTA_CTL             STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x08UL)
#define REG_GPIO_0_SWPORTB_DR              STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x0CUL)
#define REG_GPIO_0_SWPORTB_DDR             STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x10UL)
#define REG_GPIO_0_SWPORTC_DR              STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x18UL)
#define REG_GPIO_0_SWPORTC_DDR             STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x1CUL)
#define REG_GPIO_0_SWPORTD_DR              STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x24UL)
#define REG_GPIO_0_SWPORTD_DDR             STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x28UL)
#define REG_GPIO_0_INTEN                    STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x30UL)
#define REG_GPIO_0_INTMASK                 STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x34UL)
#define REG_GPIO_0_INTTYPE_LEVEL           STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x38UL)
#define REG_GPIO_0_INT_POLARITY            STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x3CUL)
#define REG_GPIO_0_INTSTATUS               STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x40UL)
#define REG_GPIO_0_RAW_INTSTATUS           STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x44UL)
#define REG_GPIO_0_DEBOUNCE                STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x48UL)
#define REG_GPIO_0_PORTA_EOI               STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x4CUL)
#define REG_GPIO_0_EXT_PORTA               STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x50UL)
#define REG_GPIO_0_EXT_PORTB               STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x54UL)
#define REG_GPIO_0_EXT_PORTC               STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x58UL)
#define REG_GPIO_0_EXT_PORTD               STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x5CUL)
#define REG_GPIO_0_INT_BOTHEDGE            STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_GPIO0_BASE_ADDR + 0x68UL)

/* 定义 Timer0 时钟、寄存器和控制位。 */
#define STARRYSKY_T1_PICO_TIMER_CLOCK_HZ         20000000UL
#define STARRYSKY_T1_PICO_TIMER0_BASE_ADDR       0x10080000UL
#define REG_TIMER_0_LOAD_COUNT              STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_TIMER0_BASE_ADDR + 0x00UL)
#define REG_TIMER_0_CURRENT_VALUE           STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_TIMER0_BASE_ADDR + 0x04UL)
#define REG_TIMER_0_CONTROL                 STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_TIMER0_BASE_ADDR + 0x08UL)
#define REG_TIMER_0_EOI                     STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_TIMER0_BASE_ADDR + 0x0CUL)
#define REG_TIMER_0_INT_STATUS              STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_TIMER0_BASE_ADDR + 0x10UL)
#define STARRYSKY_T1_PICO_TIMER_CONTROL_ENABLE   (1u << 0)
#define STARRYSKY_T1_PICO_TIMER_CONTROL_USER     (1u << 1)
#define STARRYSKY_T1_PICO_TIMER_CONTROL_MASK     (1u << 2)
#define STARRYSKY_T1_PICO_TIMER0_PLIC_SOURCE     3u

/* 定义当前机器模式上下文使用的 PLIC 寄存器。 */
#define STARRYSKY_T1_PICO_PLIC_BASE_ADDR         0x0C000000UL
#define STARRYSKY_T1_PICO_PLIC_SOURCE_COUNT      32u
#define REG_PLIC_PRIORITY(source)           STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_PLIC_BASE_ADDR + ((source) * 4u))
#define REG_PLIC_ENABLE                     STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_PLIC_BASE_ADDR + 0x002000UL)
#define REG_PLIC_THRESHOLD                  STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_PLIC_BASE_ADDR + 0x200000UL)
#define REG_PLIC_CLAIM                      STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_PLIC_BASE_ADDR + 0x200004UL)
#define REG_PLIC_COMPLETE                   STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_PLIC_BASE_ADDR + 0x200004UL)
#define STARRYSKY_T1_PICO_GPIOA_PLIC_SOURCE_BASE 8u

/* 定义系统滴答使用的 CLINT 计数寄存器。 */
#define STARRYSKY_T1_PICO_CLINT_BASE_ADDR        0x02000000UL
#define STARRYSKY_T1_PICO_CLINT_MTIME_FREQ_HZ    5000000UL
#define REG_CLINT_MTIMECMP_LOW              STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CLINT_BASE_ADDR + 0x4000UL)
#define REG_CLINT_MTIMECMP_HIGH             STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CLINT_BASE_ADDR + 0x4004UL)
#define REG_CLINT_MTIME_LOW                 STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CLINT_BASE_ADDR + 0xBFF8UL)
#define REG_CLINT_MTIME_HIGH                STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CLINT_BASE_ADDR + 0xBFFCUL)

/* 定义 SDRAM 控制器寄存器和模式设置地址。 */
#define STARRYSKY_T1_PICO_SDRAM_CTRL_BASE_ADDR   0x100B0000UL
#define REG_SDRAM_CONTROL                   STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_SDRAM_CTRL_BASE_ADDR + 0x00UL)
#define REG_SDRAM_COMMAND                   STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_SDRAM_CTRL_BASE_ADDR + 0x04UL)
#define REG_SDRAM_REFRESH                   STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_SDRAM_CTRL_BASE_ADDR + 0x08UL)
#define REG_SDRAM_MODE_ACCESS               STARRYSKY_T1_PICO_MMIO32(0x80033000UL)

/* 定义 CRU 和 PLL 寄存器，当前不提供 PLL HAL 或时钟切换。 */
#define STARRYSKY_T1_PICO_CRU_BASE_ADDR          0x100A0000UL
#define REG_CRU_CLK_CTRL                    STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CRU_BASE_ADDR + 0x008UL)
#define REG_CRU_FREQ_MEASURE_EN             STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CRU_BASE_ADDR + 0x00CUL)
#define REG_CRU_CLK_DIV                     STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CRU_BASE_ADDR + 0x010UL)
#define REG_CRU_FREQ_MEASURE0               STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CRU_BASE_ADDR + 0x028UL)
#define REG_CRU_FREQ_MEASURE1               STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CRU_BASE_ADDR + 0x02CUL)
#define REG_CRU_PLL_CTRL0                   STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CRU_BASE_ADDR + 0x040UL)
#define REG_CRU_PLL_CTRL1                   STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CRU_BASE_ADDR + 0x044UL)
#define REG_CRU_PLL_CTRL2                   STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CRU_BASE_ADDR + 0x048UL)
#define REG_CRU_PLL_CTRL3                   STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CRU_BASE_ADDR + 0x04CUL)
#define REG_CRU_SOFT_RSTN                   STARRYSKY_T1_PICO_MMIO32(STARRYSKY_T1_PICO_CRU_BASE_ADDR + 0x100UL)

#endif
