#ifndef STARTYSKY_T1_BOARD_H
#define STARTYSKY_T1_BOARD_H

#include <stdint.h>

/* 定义 StartySky T1 的存储器布局。 */
#define STARTYSKY_T1_FLASH_BASE_ADDR       0x20000000UL
#define STARTYSKY_T1_FLASH_SIZE_BYTES      0x01000000UL
#define STARTYSKY_T1_DSRAM_BASE_ADDR       0x01800000UL
#define STARTYSKY_T1_DSRAM_SIZE_BYTES      0x00004000UL
#define STARTYSKY_T1_ISRAM_BASE_ADDR       0x01000000UL
#define STARTYSKY_T1_ISRAM_TEST_SIZE_BYTES 0x00004000UL
#define STARTYSKY_T1_SDRAM_BASE_ADDR       0x80000000UL
#define STARTYSKY_T1_SDRAM_SIZE_BYTES      0x02000000UL
#define STARTYSKY_T1_SDRAM_END_ADDR        (STARTYSKY_T1_SDRAM_BASE_ADDR + \
                                            STARTYSKY_T1_SDRAM_SIZE_BYTES)

/* 定义 StartySky T1 的板级时钟。 */
#define STARTYSKY_T1_APB_CLOCK_HZ          20000000UL

/* 定义八位和三十二位易变寄存器访问方法。 */
#define STARTYSKY_T1_MMIO8(address)        (*(volatile uint8_t *)(uintptr_t)(address))
#define STARTYSKY_T1_MMIO32(address)       (*(volatile uint32_t *)(uintptr_t)(address))

/* 定义系统串口寄存器。 */
#define STARTYSKY_T1_UART0_BASE_ADDR       0x10010000UL
#define REG_UART_0_RBR                     STARTYSKY_T1_MMIO8(STARTYSKY_T1_UART0_BASE_ADDR + 0x00UL)
#define REG_UART_0_THR                     STARTYSKY_T1_MMIO8(STARTYSKY_T1_UART0_BASE_ADDR + 0x00UL)
#define REG_UART_0_DLL                     STARTYSKY_T1_MMIO8(STARTYSKY_T1_UART0_BASE_ADDR + 0x00UL)
#define REG_UART_0_DLH                     STARTYSKY_T1_MMIO8(STARTYSKY_T1_UART0_BASE_ADDR + 0x04UL)
#define REG_UART_0_LCR                     STARTYSKY_T1_MMIO8(STARTYSKY_T1_UART0_BASE_ADDR + 0x0CUL)
#define REG_UART_0_MCR                     STARTYSKY_T1_MMIO8(STARTYSKY_T1_UART0_BASE_ADDR + 0x10UL)
#define REG_UART_0_LSR                     STARTYSKY_T1_MMIO8(STARTYSKY_T1_UART0_BASE_ADDR + 0x14UL)
#define STARTYSKY_T1_UART_LSR_DATA_READY   (1u << 0)
#define STARTYSKY_T1_UART_LSR_TX_READY     (1u << 5)
#define STARTYSKY_T1_UART_LCR_DLAB         (1u << 7)
#define STARTYSKY_T1_UART_DIVISOR_MAX      0xFFFFu

/* 定义 I2C0 寄存器。 */
#define STARTYSKY_T1_I2C0_BASE_ADDR        0x10030000UL
#define REG_I2C_0_CTRL                     STARTYSKY_T1_MMIO32(STARTYSKY_T1_I2C0_BASE_ADDR + 0x00UL)
#define REG_I2C_0_PSCR                     STARTYSKY_T1_MMIO32(STARTYSKY_T1_I2C0_BASE_ADDR + 0x04UL)
#define REG_I2C_0_TXR                      STARTYSKY_T1_MMIO32(STARTYSKY_T1_I2C0_BASE_ADDR + 0x08UL)
#define REG_I2C_0_RXR                      STARTYSKY_T1_MMIO32(STARTYSKY_T1_I2C0_BASE_ADDR + 0x0CUL)
#define REG_I2C_0_CMD                      STARTYSKY_T1_MMIO32(STARTYSKY_T1_I2C0_BASE_ADDR + 0x10UL)
#define REG_I2C_0_SR                       STARTYSKY_T1_MMIO32(STARTYSKY_T1_I2C0_BASE_ADDR + 0x14UL)

/* 定义 QSPI0 寄存器。 */
#define STARTYSKY_T1_QSPI0_BASE_ADDR       0x10040000UL
#define REG_QSPI_0_CTRLR0                  STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x00UL)
#define REG_QSPI_0_CTRLR1                  STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x04UL)
#define REG_QSPI_0_SSIENR                  STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x08UL)
#define REG_QSPI_0_SER                     STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x10UL)
#define REG_QSPI_0_BAUDR                   STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x14UL)
#define REG_QSPI_0_TXFTLR                  STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x18UL)
#define REG_QSPI_0_RXFTLR                  STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x1CUL)
#define REG_QSPI_0_SR                      STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x28UL)
#define REG_QSPI_0_IMR                     STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x2CUL)
#define REG_QSPI_0_RISR                    STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x34UL)
#define REG_QSPI_0_ICR                     STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x48UL)
#define REG_QSPI_0_DR                      STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0x60UL)
#define REG_QSPI_0_SPI_CTRLR0              STARTYSKY_T1_MMIO32(STARTYSKY_T1_QSPI0_BASE_ADDR + 0xF4UL)

/* 定义 GPIO 端口数量和每组可用引脚数量。 */
#define STARTYSKY_T1_GPIO_PORT_COUNT       4u
#define STARTYSKY_T1_GPIO_PINS_PER_PORT    8u

/* 定义 GPIO 端口编号。 */
#define STARTYSKY_T1_GPIO_PORT_A           0u
#define STARTYSKY_T1_GPIO_PORT_B           1u
#define STARTYSKY_T1_GPIO_PORT_C           2u
#define STARTYSKY_T1_GPIO_PORT_D           3u

/* 定义 GPIO 数据、方向和输入寄存器。 */
#define STARTYSKY_T1_GPIO0_BASE_ADDR       0x10060000UL
#define REG_GPIO_0_SWPORTA_DR              STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x00UL)
#define REG_GPIO_0_SWPORTA_DDR             STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x04UL)
#define REG_GPIO_0_SWPORTA_CTL             STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x08UL)
#define REG_GPIO_0_SWPORTB_DR              STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x0CUL)
#define REG_GPIO_0_SWPORTB_DDR             STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x10UL)
#define REG_GPIO_0_SWPORTC_DR              STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x18UL)
#define REG_GPIO_0_SWPORTC_DDR             STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x1CUL)
#define REG_GPIO_0_SWPORTD_DR              STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x24UL)
#define REG_GPIO_0_SWPORTD_DDR             STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x28UL)
#define REG_GPIO_0_INTEN                    STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x30UL)
#define REG_GPIO_0_INTMASK                 STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x34UL)
#define REG_GPIO_0_INTTYPE_LEVEL           STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x38UL)
#define REG_GPIO_0_INT_POLARITY            STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x3CUL)
#define REG_GPIO_0_INTSTATUS               STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x40UL)
#define REG_GPIO_0_RAW_INTSTATUS           STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x44UL)
#define REG_GPIO_0_DEBOUNCE                STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x48UL)
#define REG_GPIO_0_PORTA_EOI               STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x4CUL)
#define REG_GPIO_0_EXT_PORTA               STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x50UL)
#define REG_GPIO_0_EXT_PORTB               STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x54UL)
#define REG_GPIO_0_EXT_PORTC               STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x58UL)
#define REG_GPIO_0_EXT_PORTD               STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x5CUL)
#define REG_GPIO_0_INT_BOTHEDGE            STARTYSKY_T1_MMIO32(STARTYSKY_T1_GPIO0_BASE_ADDR + 0x68UL)

/* 定义 Timer0 时钟、寄存器和控制位。 */
#define STARTYSKY_T1_TIMER_CLOCK_HZ         20000000UL
#define STARTYSKY_T1_TIMER0_BASE_ADDR       0x10080000UL
#define REG_TIMER_0_LOAD_COUNT              STARTYSKY_T1_MMIO32(STARTYSKY_T1_TIMER0_BASE_ADDR + 0x00UL)
#define REG_TIMER_0_CURRENT_VALUE           STARTYSKY_T1_MMIO32(STARTYSKY_T1_TIMER0_BASE_ADDR + 0x04UL)
#define REG_TIMER_0_CONTROL                 STARTYSKY_T1_MMIO32(STARTYSKY_T1_TIMER0_BASE_ADDR + 0x08UL)
#define REG_TIMER_0_EOI                     STARTYSKY_T1_MMIO32(STARTYSKY_T1_TIMER0_BASE_ADDR + 0x0CUL)
#define REG_TIMER_0_INT_STATUS              STARTYSKY_T1_MMIO32(STARTYSKY_T1_TIMER0_BASE_ADDR + 0x10UL)
#define STARTYSKY_T1_TIMER_CONTROL_ENABLE   (1u << 0)
#define STARTYSKY_T1_TIMER_CONTROL_USER     (1u << 1)
#define STARTYSKY_T1_TIMER_CONTROL_MASK     (1u << 2)
#define STARTYSKY_T1_TIMER0_PLIC_SOURCE     3u

/* 定义当前机器模式上下文使用的 PLIC 寄存器。 */
#define STARTYSKY_T1_PLIC_BASE_ADDR         0x0C000000UL
#define STARTYSKY_T1_PLIC_SOURCE_COUNT      32u
#define REG_PLIC_PRIORITY(source)           STARTYSKY_T1_MMIO32(STARTYSKY_T1_PLIC_BASE_ADDR + ((source) * 4u))
#define REG_PLIC_ENABLE                     STARTYSKY_T1_MMIO32(STARTYSKY_T1_PLIC_BASE_ADDR + 0x002000UL)
#define REG_PLIC_THRESHOLD                  STARTYSKY_T1_MMIO32(STARTYSKY_T1_PLIC_BASE_ADDR + 0x200000UL)
#define REG_PLIC_CLAIM                      STARTYSKY_T1_MMIO32(STARTYSKY_T1_PLIC_BASE_ADDR + 0x200004UL)
#define REG_PLIC_COMPLETE                   STARTYSKY_T1_MMIO32(STARTYSKY_T1_PLIC_BASE_ADDR + 0x200004UL)
#define STARTYSKY_T1_GPIOA_PLIC_SOURCE_BASE 8u

/* 定义系统滴答使用的 CLINT 计数寄存器。 */
#define STARTYSKY_T1_CLINT_BASE_ADDR        0x02000000UL
#define STARTYSKY_T1_CLINT_MTIME_FREQ_HZ    5000000UL
#define REG_CLINT_MTIMECMP_LOW              STARTYSKY_T1_MMIO32(STARTYSKY_T1_CLINT_BASE_ADDR + 0x4000UL)
#define REG_CLINT_MTIMECMP_HIGH             STARTYSKY_T1_MMIO32(STARTYSKY_T1_CLINT_BASE_ADDR + 0x4004UL)
#define REG_CLINT_MTIME_LOW                 STARTYSKY_T1_MMIO32(STARTYSKY_T1_CLINT_BASE_ADDR + 0xBFF8UL)
#define REG_CLINT_MTIME_HIGH                STARTYSKY_T1_MMIO32(STARTYSKY_T1_CLINT_BASE_ADDR + 0xBFFCUL)

/* 定义 SDRAM 控制器寄存器和模式设置地址。 */
#define STARTYSKY_T1_SDRAM_CTRL_BASE_ADDR   0x100B0000UL
#define REG_SDRAM_CONTROL                   STARTYSKY_T1_MMIO32(STARTYSKY_T1_SDRAM_CTRL_BASE_ADDR + 0x00UL)
#define REG_SDRAM_COMMAND                   STARTYSKY_T1_MMIO32(STARTYSKY_T1_SDRAM_CTRL_BASE_ADDR + 0x04UL)
#define REG_SDRAM_REFRESH                   STARTYSKY_T1_MMIO32(STARTYSKY_T1_SDRAM_CTRL_BASE_ADDR + 0x08UL)
#define REG_SDRAM_MODE_ACCESS               STARTYSKY_T1_MMIO32(0x80033000UL)

/* 定义 CRU 和 PLL 寄存器，当前不提供 PLL HAL 或时钟切换。 */
#define STARTYSKY_T1_CRU_BASE_ADDR          0x100A0000UL
#define REG_CRU_CLK_CTRL                    STARTYSKY_T1_MMIO32(STARTYSKY_T1_CRU_BASE_ADDR + 0x008UL)
#define REG_CRU_FREQ_MEASURE_EN             STARTYSKY_T1_MMIO32(STARTYSKY_T1_CRU_BASE_ADDR + 0x00CUL)
#define REG_CRU_CLK_DIV                     STARTYSKY_T1_MMIO32(STARTYSKY_T1_CRU_BASE_ADDR + 0x010UL)
#define REG_CRU_FREQ_MEASURE0               STARTYSKY_T1_MMIO32(STARTYSKY_T1_CRU_BASE_ADDR + 0x028UL)
#define REG_CRU_FREQ_MEASURE1               STARTYSKY_T1_MMIO32(STARTYSKY_T1_CRU_BASE_ADDR + 0x02CUL)
#define REG_CRU_PLL_CTRL0                   STARTYSKY_T1_MMIO32(STARTYSKY_T1_CRU_BASE_ADDR + 0x040UL)
#define REG_CRU_PLL_CTRL1                   STARTYSKY_T1_MMIO32(STARTYSKY_T1_CRU_BASE_ADDR + 0x044UL)
#define REG_CRU_PLL_CTRL2                   STARTYSKY_T1_MMIO32(STARTYSKY_T1_CRU_BASE_ADDR + 0x048UL)
#define REG_CRU_PLL_CTRL3                   STARTYSKY_T1_MMIO32(STARTYSKY_T1_CRU_BASE_ADDR + 0x04CUL)
#define REG_CRU_SOFT_RSTN                   STARTYSKY_T1_MMIO32(STARTYSKY_T1_CRU_BASE_ADDR + 0x100UL)

#endif
